"""baseline connections and annotations

Revision ID: 9105935b4e82
Revises: 
Create Date: 2026-07-22 12:49:10.247968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9105935b4e82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('db_type', sa.String(length=32), nullable=False),
    sa.Column('url_encrypted', sa.Text(), nullable=False),
    sa.Column('dbname', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_connections')),
    sa.UniqueConstraint('name', name=op.f('uq_saved_connections_name'))
    )
    op.create_table('schema_annotations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['saved_connections.id'], name=op.f('fk_schema_annotations_connection_id_saved_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schema_annotations')),
    sa.UniqueConstraint('connection_id', 'schema_name', 'table_name', 'column_name', name='uq_schema_annotations_key')
    )
    op.create_index(op.f('ix_schema_annotations_connection_id'), 'schema_annotations', ['connection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_annotations_connection_id'), table_name='schema_annotations')
    op.drop_table('schema_annotations')
    op.drop_table('saved_connections')
    # ### end Alembic commands ###
